services:
  internet-shop:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./store:/store #связывает локальную папку с папкой в контейнере.

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"