# Generated by Django 4.1.1 on 2023-03-21 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SmallIntegerField()),
                ('model', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=40)),
                ('operating_system', models.CharField(choices=[('HO', 'Windows 10 Home'), ('PR', 'Windows 10 PRO'), ('WI', 'Windows 11'), ('LI', 'Linux')], default='HO', max_length=2)),
                ('category', models.ForeignKey(default='Электротехника', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_productDetail_1', to='product.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodDetail_1', to='product.product')),
            ],
            options={
                'ordering': ('product', 'uid'),
            },
        ),
        migrations.CreateModel(
            name='MonitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SmallIntegerField()),
                ('model', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=40)),
                ('diagonal', models.FloatField()),
                ('resolution', models.CharField(max_length=20)),
                ('brightness', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('connector_VGA', models.BooleanField()),
                ('connector_HDMI', models.BooleanField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('category', models.ForeignKey(default='Электротехника', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_productDetail_2', to='product.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodDetail_2', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
