# Generated by Django 4.1.1 on 2023-03-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_laptopdetails_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopdetails',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='laptopdetails',
            name='frequency',
            field=models.CharField(choices=[('0', 'No info'), ('1', '60'), ('2', '144'), ('3', '160'), ('4', '240'), ('5', '360')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='laptopdetails',
            name='model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='brightness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='diagonal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='frequency',
            field=models.CharField(choices=[('0', 'No info'), ('1', '60'), ('2', '144'), ('3', '160'), ('4', '240'), ('5', '360')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='model',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitordetails',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
