# Generated by Django 4.1.1 on 2023-03-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_laptopdetails_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopdetails',
            name='operating_system',
            field=models.CharField(choices=[('Windows 10 Home', 'Windows 10 home'), ('Windows 10 PRO', 'Windows 10 PRO'), ('Windows 11 home', 'Windows 11 home'), ('Windows 11 pro', 'Windows 11 pro'), ('Linux', 'Linux'), ('Mac OS', 'Mac OS'), ('Without OS', 'Without OS')], default='No info', max_length=50),
        ),
        migrations.AlterField(
            model_name='laptopdetails',
            name='screen_type',
            field=models.CharField(choices=[('No info', 'No info'), ('IPS', 'IPS'), ('IGZO', 'IGZO'), ('VA', 'VA'), ('TN+Film', 'TN+Film'), ('OLED', 'OLED'), ('other', 'other')], default='0', max_length=50),
        ),
    ]
