# Generated by Django 4.1.1 on 2023-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_laptopdetails_operating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopdetails',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptopdetails',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptopdetails',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
