# Generated by Django 4.1.1 on 2023-03-26 14:50

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_laptopdetails_color_alter_laptopdetails_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboarddetails',
            name='uid',
            field=models.CharField(default=product.models.add_uniq_uid, max_length=14, unique=True),
        ),
    ]
