# Generated by Django 4.1.1 on 2023-03-27 12:16

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_keyboarddetails_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboarddetails',
            name='color',
            field=models.CharField(choices=[('Нет информации', 'no info'), ('Чёрный', 'Black'), ('Белый', 'White'), ('Зелёный', 'Green'), ('Красный', 'Red'), ('Синий', 'Blue'), ('Жёлтый', 'Yellow')], default='no info', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='keyboarddetails',
            name='function_key',
            field=models.BooleanField(default=False, verbose_name='Клавиша функции'),
        ),
        migrations.AlterField(
            model_name='keyboarddetails',
            name='programmable_keys',
            field=models.BooleanField(default=False, verbose_name='Программируемые клавиши'),
        ),
        migrations.CreateModel(
            name='VideoCardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=product.models.add_uniq_uid, max_length=14, unique=True, verbose_name='Уникальный идентификатор')),
                ('model', models.CharField(max_length=200, verbose_name='Модель')),
                ('color', models.CharField(choices=[('Нет информации', 'no info'), ('Чёрный', 'Black'), ('Белый', 'White'), ('Зелёный', 'Green'), ('Красный', 'Red'), ('Синий', 'Blue'), ('Жёлтый', 'Yellow')], default='no info', max_length=20, verbose_name='Цвет')),
                ('gpu', models.CharField(default='no info', max_length=200, verbose_name='Графический процессор')),
                ('microarchitecture', models.CharField(default='no info', max_length=200, verbose_name='Микроархитектура')),
                ('videomemory_size', models.CharField(choices=[('Нет информации', 'no info'), ('4', '4 ГБ'), ('6', '6 ГБ'), ('8', '8 ГБ')], default='no info', max_length=20, verbose_name='Размер видеопамяти')),
                ('memory_type', models.CharField(choices=[('no info', 'no info'), ('DDR3', 'DDR3'), ('GDDR3', 'GDDR3'), ('GDDR4', 'GDDR4'), ('GDDR5', 'GDDR5'), ('GDDR6', 'GDDR6')], default='no info', max_length=20, verbose_name='Тип памяти')),
                ('frequency_videochip', models.IntegerField(default='0', verbose_name='Штатная частота работы видеочипа')),
                ('ray_tracing_support', models.BooleanField(default=False, verbose_name='Поддержка трассировки лучей')),
                ('number_texture_units', models.IntegerField(default='0', verbose_name='Число текстурных блоков')),
                ('video_connectors_displayport', models.BooleanField(default=False, verbose_name='видеоразъём displayport')),
                ('video_connectors_hdmi', models.BooleanField(default=False, verbose_name='видеоразъём hdmi')),
                ('length', models.IntegerField(default='0', verbose_name='Длина, мм')),
                ('width', models.IntegerField(default='0', verbose_name='Ширина, мм')),
                ('weight', models.IntegerField(default='0', verbose_name='Вес, г')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideocardDetails', to='product.product')),
            ],
        ),
    ]
